baseURL = 'https://pehtheme-hugo.netlify.app/'
languageCode = 'fr-ch'
title = 'Laboratoire de veille technologique'
theme = 'pehtheme-hugo'

summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4
disqusShortname = 'your-disqus-shortname' # <- Get form here : https://disqus.com

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'Laboratoire de veille technologique - Explorez les dernières innovations et tendances du monde numérique.'
	mainSections = 'posts'

[author]
	name = 'Anthony Arphan'
	bio = 'Debitis assumenda esse dignissimos aperiam delectus maxime tenetur repudiandae dolore'
	avatar = '/images/nasa-astronaut-unsplash.jpg'
	twitter = 'https://twitter.com/insertapps'

[pagination]
	pagerSize = 6 # <- Set the desired number of posts per page 

[menu] # Menu management
	[[menu.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'À propos'
		pageRef = '/about'
		weight = 15
	[[menu.main]]
		name = 'Blog'
		pageRef = '/posts'
		weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'